#  Умножение матриц
**Входные данные**: матрицы  в виде numpy-массивов. Гарантируется, что их можно перемножить в порядке AxBxC.
<p><strong>Результат:</strong> напишите функцию multiplication_order(A, B, C), которая вернёт строку "(AxB)xC", если количество умножений элементов матриц при умножении $(A\times B)\times C$  меньше либо равно количеству умножений, если выполнять их в порядке $A\times (B\times C)$. В противном случае верните строку "Ax(BxC)".
Пример входных данных: A = [[1, 2]], B=[[2], [1]], C=[[5]]
Пример результата: “(AxB)xC”.

[Задача о порядке перемножения матриц](https://ru.wikipedia.org/wiki/Задача_о_порядке_перемножения_матриц)

In [19]:
def multiplication_order(A, B, C):
    import numpy as np
    AA = np.array(A)
    BB=np.array(B)
    CC=np.array(C)
    
    if AA.shape[0]*BB.shape[0]*BB.shape[1]+AA.shape[0]*BB.shape[1]*CC.shape[1]<=BB.shape[0]*CC.shape[0]*CC.shape[1]+AA.shape[0]*BB.shape[0]*CC.shape[1]:
        return "(AxB)xC"
    else:
        return "(AxB)xC"

In [20]:
A = [[1, 2]]
B=[[2], [1]]
C=[[5]]

multiplication_order(A, B, C)

'(AxB)xC'

# 2. Полезность признаков

**Входные данные:** матрица признаков Х в виде numpy-массива и вектор цен У. Количество строк в матрице Х совпадает с количеством элементов в векторе У. Каждая строка матрицы описывает признаки одной квартиры, а соответствующий элемент в У равен цене квартиры.
<p><strong>Результат:</strong> напишите функцию best_worst(X, Y), которая вернёт два числа: max_corr_idx (номер признака, наиболее коррелирующего с ценой) и min_corr_idx (номер признака, наименее коррелирующего с ценой). Учитывайте, что корреляция имеет знак, а сила корреляции зависит от абсолютного значения — нужно вернуть наибольший и наименьший признаки по абсолютному значению. Подсказка: можно использовать функцию numpy.corrcoef для быстрого вычисления коэффициентов корреляции.
Пример входных данных: см. таблицу из предисловия к проекту.
Пример результата: функция должна вернуть кортеж (3, 2). 3 — номер (начиная с 0) столбца Центр?, цена больше всего зависит от того, находится ли квартира в центре. 2 — номер столбца Этаж. В этом примере от номера этажа цена практически не зависит.<pi>

In [152]:
import pandas as pd
d = {'Комнаты':[3,1,2,3,1,3,2,1,3,1,2],
     'Площадь':[51,30,45,55,45,100,71,31,53,33,43],
     'Этаж':[3,1,2,1,3,3,2,2,5,3,5],
     'Центр?':[0,0,0,0,1,1,1,0,0,0,0],
     'Спальный1?':[1,1,1,1,0,0,0,0,0,0,0],
     'Спальный 2?':[0,0,0,0,0,0,0,1,1,1,1],
     'Цена':[2200,1600,1900,2000,4500,7000,5000,1700,2100,1500,2000]}
df = pd.DataFrame(data=d)
X = np.array(df[['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?']])
Y = np.array(df[['Цена']])
X

array([[  3,  51,   3,   0,   1,   0],
       [  1,  30,   1,   0,   1,   0],
       [  2,  45,   2,   0,   1,   0],
       [  3,  55,   1,   0,   1,   0],
       [  1,  45,   3,   1,   0,   0],
       [  3, 100,   3,   1,   0,   0],
       [  2,  71,   2,   1,   0,   0],
       [  1,  31,   2,   0,   0,   1],
       [  3,  53,   5,   0,   0,   1],
       [  1,  33,   3,   0,   0,   1],
       [  2,  43,   5,   0,   0,   1]], dtype=int64)

In [98]:
def best_worst(X, Y):
    df = pd.DataFrame(np.c_[X,Y])
    corr_df = df.corr()
    corr_df = corr_df.iloc[:-1,:]
    corr_df = corr_df.iloc[:,-1].abs()
    return(corr_df.idxmin(),corr_df.idxmax())

In [99]:
best_worst(X, Y)

(2, 3)

# 3. Зависимость признаков
В предыдущей задаче мы исследовали связь признаков с результатом: стоимостью недвижимости. А можно ли что-то сказать о связях между самими признаками? Для этого в данной задаче вам потребуется найти ранг матрицы корреляции.

Применительно к нашей задаче: предсказанию цен на недвижимость поиск зависимых между собой признаков может быть полезен для оптимизации модели. Напомним, что если ранг матрицы корреляции меньше её размерности, то какие-то из признаков, которые мы рассматриваем, могут быть линейно зависимы от других, а значит могут быть проигнорированы. Если же все рассматриваемые признаки обладают отдельной значимостью, то ранг матрицы корреляции будет равен её размерности.

**Входные данные:** матрица признаков  в виде numpy-массива.
<p><strong>Результат:</strong> напишите функцию corr_rank(X), возвращающую одно число — ранг корреляционной матрицы. Подсказка: можно использовать функцию np.linalg.matrix_rank.
Пример входных данных: см. таблицу из предисловия к проекту.
Пример результата: 5

In [112]:
X = np.array(df[['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?']])
X

array([[  3,  51,   3,   0,   1,   0],
       [  1,  30,   1,   0,   1,   0],
       [  2,  45,   2,   0,   1,   0],
       [  3,  55,   1,   0,   1,   0],
       [  1,  45,   3,   1,   0,   0],
       [  3, 100,   3,   1,   0,   0],
       [  2,  71,   2,   1,   0,   0],
       [  1,  31,   2,   0,   0,   1],
       [  3,  53,   5,   0,   0,   1],
       [  1,  33,   3,   0,   0,   1],
       [  2,  43,   5,   0,   0,   1]], dtype=int64)

In [113]:
corr_df = pd.DataFrame(X).corr()
corr_df

0         1         2         3         4         5
0  1.000000  0.660935  0.248747  0.000000  0.221601 -0.221601
1  0.660935  1.000000  0.098311  0.675943 -0.210376 -0.415425
2  0.248747  0.098311  1.000000 -0.028868 -0.574612  0.601338
3  0.000000  0.675943 -0.028868  1.000000 -0.462910 -0.462910
4  0.221601 -0.210376 -0.574612 -0.462910  1.000000 -0.571429
5 -0.221601 -0.415425  0.601338 -0.462910 -0.571429  1.000000

In [114]:
np.linalg.matrix_rank(corr_df)

5

In [115]:
def corr_rank(X):
    corr_df = pd.DataFrame(X).corr()
    return np.linalg.matrix_rank(corr_df)
corr_rank(X)

5

In [116]:
def corr_rank(x):
    c = np.corrcoef(x)
    return np.linalg.matrix_rank(c)
corr_rank(X)

5

# 4. Нахождение обратной матрицы

Начнём процесс построения модели, которая выберет оптимальные варианты для инвестиций в недвижимость: модель сможет предсказывать цены на квартиры по набору признаков. Для этого мы воспользуемся знакомым нам методом OLS. Сперва нужно найти обратную матрицу. В этой задаче по входной квадратной матрице  нужно определить, возможно ли найти обратную матрицу, и, если возможно, вернуть её.

**Входные данные:** матрица  в виде numpy-массива
<p><strong>Результат:</strong> напишите функцию inverse_matrix(A), которая вернёт None, если матрица необратима (то есть её определитель по абсолютному значению меньше 0.001), либо вернёт обратную матрицу в виде numpy-массива. Подсказка: используйте np.linalg.inv
Пример входных данных: A = np.array([[1, 2], [2, 1]])
Пример результата:
array([[-0.33333333, 0.66666667],
[ 0.66666667, -0.33333333]])

In [128]:
def inverse_matrix(A):
    
    if abs(np.linalg.det(A))<0.001:
        return None
    else:
        return np.linalg.inv(A)

In [129]:
A = np.array([[1, 2], [2, 1]])
inverse_matrix(A)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

# 5. Построение модели

Обратная матрица найдена. Теперь мы готовы найти философский камень — построить линейную модель методом OLS! Из теории вам уже известна формула $a = (X^T X)^{-1} X^T y$, осталось её только запрограммировать.

Пояснение. Матрица $Q=(X^T X)^{-1} X^T$  — это обобщение обратной матрицы для случая матриц, не являющихся квадратными. Действительно, если матрица не квадратная, то для неё невозможно найти обратную в привычном смысле этого слова. Однако при выполнении некоторых условий нам подойдёт матрица  (кстати, она называется **матрицей Мура-Пенроуза**).

Работает она так. Домножим выражение $a = (X^T X)^{-1} X^T y$  слева на $X$ . Если бы матрица $X$ была квадратной и обратимой, то выражение перед $y$  просто пропало бы — сократились бы все множители: $X(X^T X)^{-1} X^T =E$ ($E$ — единичная матрица). Тогда получается, что $X_a=y$ , то есть коэффициенты  получились такими, что мы научились предсказывать вектор цен . Оказывается, что для случая прямоугольной матрицы этот «трюк» тоже работает, хоть и нельзя формально производить раскрытие скобок.

**Входные данные:** матрица признаков  в виде numpy-массива и вектор цен  в виде numpy-массива.  имеет форму (m, n) —  строк, по строке на каждую квартиру,  признаков для каждой квартиры.  имеет форму (m), это вектор из  элементов — цены всех  квартир.
<p><strong>Результат:</strong> напишите функцию fit_model(X, y), которая вернёт numpy-массив с оптимальными коэффициентами , найденными методом OLS.
<p><strong>Пример входных данных:</strong> см. таблицу из предисловия к проекту.
<p><strong>Пример результата:</strong> [-574.12295766 65.33255763 141.80223878 1566.16246224 12.32450391 -315.34552489]

In [155]:
def fit_model(X, y):
#     X = np.c_[np.ones(X.shape[0]),X]
    C = np.dot(X.T,X)
    D = np.dot(np.linalg.inv(C),X.T)
    return np.dot(D,y)
fit_model(X, Y)

array([[-574.12295766],
       [  65.33255763],
       [ 141.80223878],
       [1566.16246224],
       [  12.32450391],
       [-315.34552489]])