In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 8, 10,  6],
       [11,  8,  6],
       [ 8,  8, 10]])

In [4]:
B

array([[ 0, -2,  1],
       [ 0,  0,  0],
       [ 2,  1,  0]])

In [5]:
# Поэлементное умножение
A*B

array([[  0, -20,   6],
       [  0,   0,   0],
       [ 16,   8,   0]])

In [11]:
# тип np.matrix
# но такой способ не часто употребим в программировании, тк numpy.matrix частный случай ndarrays. 
#matrix - это двумерный массив и не рекомендуется использовать этот класс, тк он будет удален
#
A_m=np.matrix(A)
B_m=np.matrix(B)
print('A_m',type(A_m))
print('B_m',type(B_m))
print(A_m*B_m)

A_m <class 'numpy.matrix'>
B_m <class 'numpy.matrix'>
[[ 12 -10   8]
 [ 12 -16  11]
 [ 20  -6   8]]


In [12]:
# Матричное умножение
np.dot(A,B)

array([[ 12, -10,   8],
       [ 12, -16,  11],
       [ 20,  -6,   8]])

In [13]:
# Матричное умножение
A@B

array([[ 12, -10,   8],
       [ 12, -16,  11],
       [ 20,  -6,   8]])

In [14]:
# Порядок умножения AB != BA
B@A

array([[-14,  -8,  -2],
       [  0,   0,   0],
       [ 27,  28,  18]])

In [15]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[8 8 5 9 6]
 [8 7 5 8 5]
 [8 9 6 5 6]]
B:
 [[ 0 -2]
 [ 2  2]
 [ 1  0]
 [-2 -2]
 [ 1  0]]


In [16]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[  9, -18],
       [  8, -18],
       [ 20,  -8]])

In [17]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [18]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [19]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-4 -4 -1  2]
 [ 1 -4 -2 -1]
 [-3 -2 -3  3]
 [ 2 -1 -4 -1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-4 -8  0 -2]
 [ 1 -8  0  1]
 [-3 -4  0 -3]
 [ 2 -2  0  1]]
DA:
 [[-4 -4 -1  2]
 [ 2 -8 -4 -2]
 [ 0  0  0  0]
 [-2  1  4  1]]


In [20]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [21]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [22]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [23]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [24]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [25]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [26]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

# Задачи

Даны матрица A и вектор $\vec{x}$

In [27]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

Найдите произведение матрицы  и вектора  в том порядке, в котором их можно умножить.

In [28]:
A@x

array([26, 30])

Даны две матрицы:

In [29]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

In [31]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Дана система векторов:

In [32]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Найдите матрицу Грама системы векторов x,y,z

In [36]:
A=np.array([x,y,z])
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [38]:
import pandas as pd
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

Найдите вектор выручки Бориса.

In [ ]:
A = df.values


In [46]:
Count_DF.loc['Борис'].values*Price_DF.loc['Борис'].values

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [44]:

Price_DF.loc['Борис'].values

array([1.8, 2.5, 1. , 1. , 1. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [54]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [78]:
((Price_DF*com)@Count_DF.T).values.diagonal()

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Найдите вектор прибыли стилистов.

In [73]:
Count_DF.T

Аня  Борис  Вика  Галя  Дима  Егор  Женя  Юра
Женские стрижки   10      2    12     4     6    10    22    7
Мужские стрижки    5     21    12     8    25     3     1    0
Окрашивания       12      3     0    18    27     2     4   31
Укладка           15     25    30    14    25    17    25   31
Уход              10      6     4     5    18    12    20   28

In [75]:
Price_DF*com

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               0.40             0.30         0.30     0.08  0.10
Борис             0.36             0.50         0.30     0.10  0.10
Вика              0.40             0.40         0.00     0.05  0.20
Галя              0.36             0.24         0.84     0.08  0.20
Дима              0.50             0.70         0.60     0.10  0.15
Егор              1.00             1.00         0.90     0.20  0.25
Женя              0.22             0.20         0.45     0.05  0.17
Юра               0.90             0.80         0.75     0.10  0.20

In [83]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
anti_com = np.array([1,1,1,1,1])-com
anti_com

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [84]:
((Price_DF*anti_com)@Count_DF.T).values.diagonal()

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])